import './loc_base.dart';

enum LKeys {
  editJob,
  errorOccurred,
  pleaseTryLater,
  name,
  pleaseProvideName,
  color,
  pleaseChooseColor,
  back,
  unsavedDataLost,
  yourJobsList,
  yourRecords,
  nOJustLooking,
  areYouSureWantToDeleteIt,
  isDone,
  someJob,
  sevenD,
  sixD,
  fiveD,
  fourD,
  threeD,
  twoD,
  oneD,
  today,
  blue,
  yellow,
  brown,
  red,
  purple,
  pink,
  green,
  black,
  orange,
  date,
  time,
  privacyPolicy,
}

abstract class LocApp {
  static final Map<String, Map<LKeys, String>> _db = {
    "en": {
      LKeys.editJob: "Edit Job",
      LKeys.errorOccurred: "Error occurred.",
      LKeys.pleaseTryLater: "Please try later.",
      LKeys.name: "name",
      LKeys.pleaseProvideName: "Please provide a name.",
      LKeys.color: "Color",
      LKeys.pleaseChooseColor: "Please choose a color.",
      LKeys.back: "Back?",
      LKeys.unsavedDataLost: "Unsaved data will be lost.",
      LKeys.yourJobsList: "Your jobs list",
      LKeys.yourRecords: "Your records",
      LKeys.nOJustLooking: "NO(Just Looking)",
      LKeys.areYouSureWantToDeleteIt: "Are You Sure Want To Delete It?",
      LKeys.isDone: " is done?",
      LKeys.someJob: "some job",
      LKeys.sevenD: "7d",
      LKeys.sixD: "6d",
      LKeys.fiveD: "5d",
      LKeys.fourD: "4d",
      LKeys.threeD: "3d",
      LKeys.twoD: "2d",
      LKeys.oneD: "1d",
      LKeys.today: "Today",
      LKeys.blue: "Blue",
      LKeys.yellow: "Yellow",
      LKeys.brown: "Brown",
      LKeys.red: "Red",
      LKeys.purple: "Purple",
      LKeys.pink: "Pink",
      LKeys.green: "Green",
      LKeys.black: "Black",
      LKeys.orange: "Orange",
      LKeys.date: "Date",
      LKeys.time: "Time",
      LKeys.privacyPolicy: "Privacy Policy",
    },
    "ja": {
      LKeys.editJob: "お仕事の登録",
      LKeys.errorOccurred: "エラーが発生しました。",
      LKeys.pleaseTryLater: "もう一度試してください。",
      LKeys.name: "名前",
      LKeys.pleaseProvideName: "名前を入力してください。",
      LKeys.color: "色",
      LKeys.pleaseChooseColor: "色を選んでください。",
      LKeys.back: "前の画面に戻りますか？",
      LKeys.unsavedDataLost: "入力中のデータは消えます。",
      LKeys.yourJobsList: "お仕事の一覧",
      LKeys.yourRecords: "あなたの記録",
      LKeys.nOJustLooking: "NO(見るだけ)",
      LKeys.areYouSureWantToDeleteIt: "本当に消しますか？",
      LKeys.isDone: " は終わりましたか？",
      LKeys.someJob: "あるお仕事",
      LKeys.sevenD: "7日",
      LKeys.sixD: "6日",
      LKeys.fiveD: "5日",
      LKeys.fourD: "4日",
      LKeys.threeD: "3日",
      LKeys.twoD: "2日",
      LKeys.oneD: "1日",
      LKeys.today: "今日",
      LKeys.blue: "青",
      LKeys.yellow: "黄色",
      LKeys.brown: "茶色",
      LKeys.red: "赤",
      LKeys.purple: "紫",
      LKeys.pink: "ピンク",
      LKeys.green: "緑",
      LKeys.black: "黒",
      LKeys.orange: "オレンジ",
      LKeys.date: "日付",
      LKeys.time: "時刻",
      LKeys.privacyPolicy: "プライバシーポリシー",
    },
  };

  static String translate(LKeys value) {
    return _db[LocBase.language]?[value] ?? "-";
  }
}
